import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { NotificationProvider } from '@/contexts/notification.context';
import ChatWidget from "@/components/chat/chat-widget";

import '@/app/globals.css';
import NextAuthWrapper from "@/library/next.auth.wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SmartHotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <NextAuthWrapper>
            <NotificationProvider>
              {children}
              <ChatWidget />
            </NotificationProvider>
          </NextAuthWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
