import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { NotificationProvider } from '@/contexts/notification.context';
import ChatWidget from "@/components/chat/chat-widget";
import { auth } from "@/auth";

import '@/app/globals.css';
import NextAuthWrapper from "@/library/next.auth.wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SmartHotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthWrapper session={session}>
          <AntdRegistry>
            <NotificationProvider>
              {children}
              <ChatWidget />
            </NotificationProvider>
          </AntdRegistry>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
